language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # Build
  - docker-compose -f docker-compose-build.yaml build --parallel

  # Tagging
  - docker tag udagram-api-feed hoangthiendocker/udagram-api-feed:v1
  - docker tag udagram-api-user hoangthiendocker/udagram-api-user:v1
  - docker tag udagram-frontend hoangthiendocker/udagram-frontend:local
  - docker tag udagram-reverseproxy hoangthiendocker/udagram-reverseproxy:v1

after_success:
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hoangthiendocker/udagram-api-feed:v1
  - docker push hoangthiendocker/udagram-api-user:v1
  - docker push hoangthiendocker/udagram-frontend:local
  - docker push hoangthiendocker/udagram-reverseproxy:v1