language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # Build
  - docker build -t udgram-reverseproxy ./udagram-reverseproxy
  - docker build -t udgram-api-feed ./udagram-api-feed
  - docker build -t udgram-api-user ./udagram-api-user
  - docker build -t udgram-frontend ./udagram-frontend
  # Tagging
  - docker tag udagram-api-feed hoangthiendocker/udagram-api-feed:latest
  - docker tag udagram-api-user hoangthiendocker/udagram-api-user:latest
  - docker tag udagram-frontend hoangthiendocker/udagram-frontend:latest
  - docker tag udagram-reverseproxy hoangthiendocker/udagram-reverseproxy:latest

after_success:
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hoangthiendocker/udagram-api-feed:latest
  - docker push hoangthiendocker/udagram-api-user:latest
  - docker push hoangthiendocker/udagram-frontend:latest
  - docker push hoangthiendocker/udagram-reverseproxy:latest