language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # Build & tag
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy hoangthiendocker/reverseproxy:v1

  - docker build -t backend-feed ./udagram-api-feed
  - docker tag backend-feed hoangthiendocker/backend-feed:v1

  - docker build -t backend-user ./udagram-api-user
  - docker tag backend-user hoangthiendocker/backend-user:v1

  - docker build -t frontend ./udagram-frontend
  - docker tag frontend hoangthiendocker/frontend:v2

after_success:
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hoangthiendocker/backend-feed:v1
  - docker push hoangthiendocker/backend-user:v1
  - docker push hoangthiendocker/frontend:v2
  - docker push hoangthiendocker/reverseproxy:v1