apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    service: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
        api: external
    spec:
      containers:
      - name: udagram-frontend
        image: hoangthiendocker/frontend:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1000m